// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rindus.reservationdemo.web;

import com.rindus.reservationdemo.web.ProductsItemPreciosPorProductoThymeleafController;
import com.rindus.reservationdemo.web.ProductsItemPreciosPorProductoThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect ProductsItemPreciosPorProductoThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: ProductsItemPreciosPorProductoThymeleafLinkFactory implements MethodLinkFactory<ProductsItemPreciosPorProductoThymeleafController>;
    
    declare @type: ProductsItemPreciosPorProductoThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.REMOVEFROMPRECIOSPORPRODUCTO = "removeFromPreciosPorProducto";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.REMOVEFROMPRECIOSPORPRODUCTOBATCH = "removeFromPreciosPorProductoBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProductsItemPreciosPorProductoThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<ProductsItemPreciosPorProductoThymeleafController> ProductsItemPreciosPorProductoThymeleafLinkFactory.getControllerClass() {
        return ProductsItemPreciosPorProductoThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents ProductsItemPreciosPorProductoThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMPRECIOSPORPRODUCTO)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromPreciosPorProducto(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMPRECIOSPORPRODUCTOBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromPreciosPorProductoBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
